### ISSUE TITLE
AttributeError: 'PrinterProbe' object has no attribute 'sample_count'

### ISSUE THREAD

**Issue by Wizzkiss** [protoloft/klipper_z_calibration#144]
File "/home/pi/klipper/klippy/extras/z_calibration.py", line 110, in handle_connect
    self.samples = probe.sample_count
AttributeError: 'PrinterProbe' object has no attribute 'sample_count'

after update klipper to v0.12.0-229-g589bd64c

**Comment by TitusLabs** [comment]
Please update to the recent version :+1:

**Comment by jojodroopy** [comment]
Hello, since this update my auto offset Z no longer works. Internal error is indicated

**Comment by jojodroopy** [comment]
> Hello, since this update my auto offset Z no longer works. Internal error is indicated

after update klipper to v0.12.0-229-g589bd64c

**Comment by jojodroopy** [comment]
> > Hello, since this update my auto offset Z no longer works. Internal error is indicated
> 
> after update klipper to v0.12.0-229-g589bd64c

[===== Config file =====.txt](https://github.com/user-attachments/files/15792230/Config.file.txt)

**Comment by Wizzkiss** [comment]
Update z_calibration via moonraker Update Manager

**Comment by TitusLabs** [comment]
Please update to the recent version :+1: 

> > > Hello, since this update my auto offset Z no longer works. Internal error is indicated
> > 
> > 
> > after update klipper to v0.12.0-229-g589bd64c
> 
> [===== Config file =====.txt](https://github.com/user-attachments/files/15792230/Config.file.txt)

Sorry, wrong place! That's not my z calibration plugin. Mine does not even work with a bltouch..

**Comment by jojodroopy** [comment]
Ah... sorry, I'm bad at English and the translations are not always very reliable. For me the Bltouch works perfectly, it's just that since the last Klipper update, the auto Z offset no longer works.
So good luck with your machine... ;-)

**Comment by ashinckley** [comment]
I've encountered this issue as well.  I'm trying to figure out how to fix it.
After updating Klipper (currently on v0.12.0-239-g433fcb6f)
I get the same error: "Internal error during connect: 'PrinterProbe' object has no attribute 'sample_count'"
I've updated your plugin via  update manager through moonraker to v1.1.0-0-gabbe9c4d

**Comment by ashinckley** [comment]
Apologies.  I thing I fixed it.  Not sure what happened, but I simply reinstalled, and it seems to work now:
For those who might have also encountered this error, this seemed to do the trick.
cd ~
git clone https://github.com/protoloft/klipper_z_calibration.git
./klipper_z_calibration/install.sh

**Comment by jojodroopy** [comment]
Ok, thank you very much I will try that

Good luck and nice day

 

De : ashinckley ***@***.***> 
Envoyé : mardi 18 juin 2024 06:32
À : protoloft/klipper_z_calibration ***@***.***>
Cc : Joël ***@***.***>; Comment ***@***.***>
Objet : Re: [protoloft/klipper_z_calibration] AttributeError: 'PrinterProbe' object has no attribute 'sample_count' (Issue #144)

 

Apologies. I think I fixed it. Not sure what happened, but I simply reinstalled, and it seems to work now:
For those who might have also encountered this error, this seemed to do the trick.
cd ~
git clone https://github.com/protoloft/klipper_z_calibration.git
./klipper_z_calibration/install.sh

**Comment by jojodroopy** [comment]
Unfortunately, it doesn't work for me... I still have this internal error... I'll look again, but I don't know where. Thank you all the same for your help.

 

De : ashinckley ***@***.***> 
Envoyé : mardi 18 juin 2024 06:32
À : protoloft/klipper_z_calibration ***@***.***>
Cc : Joël ***@***.***>; Comment ***@***.***>
Objet : Re: [protoloft/klipper_z_calibration] AttributeError: 'PrinterProbe' object has no attribute 'sample_count' (Issue #144)

 

Apologies. I think I fixed it. Not sure what happened, but I simply reinstalled, and it seems to work now:
For those who might have also encountered this error, this seemed to do the trick.
cd ~
git clone https://github.com/protoloft/klipper_z_calibration.git
./klipper_z_calibration/install.sh

**Comment by TitusLabs** [comment]
@jojodroopy I'm sorry, I meant to say that you were using a completely different plugin (auto offset z). Please contact the correct creator. My plugin has long since been fixed in this respect.

...ok, now you are using it. And that works for you? With a BLTouch??

**Comment by jojodroopy** [comment]
No, that doesn't work. I use a Bltouch and before the Klipper update everything worked perfectly. Now even the input shaper also doesn't work anymore. What plugin do you use instead of auto offset z?

**Comment by TitusLabs** [comment]
Your log tells me that you used this one: https://github.com/hawkeyexp/auto_offset_z

**Comment by sanketss84** [comment]
> Update z_calibration via moonraker Update Manager

much thanks this solved my issue.
